### ISSUE TITLE
Investigate Bing search api

### ISSUE THREAD

**Issue by knowtheory** [knowtheory/lmgtdfy#4]
- [x] What are the API limits?
- [x] Is there a python library for accessing the API?
- [x] What keys/secrets do we need to access the API?
- [x] What info do we need to sign up for the API?
- [x] How much does API access cost?

**Comment by pavel-i-am** [comment]
Cost of API varies depending on the number of queries per month.
Key generation: https://datamarket.azure.com/account/keys
Other general documentation: http://datamarket.azure.com/dataset/bing/search
